global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'stoic_citadel'
    static_configs:
      - targets: ['freqtrade:8000'] # Exporter host and port (container name)
    metrics_path: '/metrics'